import type { Metadata } from "next";
import { Inter, Noto_Serif, Source_Code_Pro } from "next/font/google";

import "@/styles/reset.scss";
import "@/styles/globals.scss";

import { FontsProvider, ThemeProvider } from "@/providers";
import { Navbar } from "@/components";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const noto_serif = Noto_Serif({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const source_code_pro = Source_Code_Pro({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// TODO CAMBIAR LA METADATA
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${noto_serif.variable} ${source_code_pro.variable}`}>
        <FontsProvider>
          <ThemeProvider>
            <div className="layout">
              <Navbar />
              {children}
            </div>
          </ThemeProvider>
        </FontsProvider>
      </body>
    </html>
  );
}
